name: Deploy to Local Kubernetes

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate random pod name
        id: generate
        shell: bash
        run: echo "RANDOM_ID=$RANDOM" >> $GITHUB_ENV

      - name: Show random pod name
        shell: bash
        run: |
          echo "Generated Pod name: mypod-${{ env.RANDOM_ID }}"

      - name: Replace variable in pod.yaml and apply
        shell: bash
        run: |
          sed "s/\${RANDOM_ID}/${{ env.RANDOM_ID }}/g" pod.yaml > pod-temp.yaml
          kubectl apply -f pod-temp.yaml

      - name: Verify pods
        shell: bash
        run: |
          kubectl get pods -o wide
